version: '3'

services:
  postgres:
    container_name: 'justKeepAtIt-postgres'
    restart: unless-stopped
    image: 'postgres:13'
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '15432:5432'
    volumes:
      - 'postgresData:/var/lib/postgresql/data/'

volumes:
  postgresData: {}
